# Will be a bash file which does the following:
# Creates directory for pictures
# Launches a Python program to build the lynx logfile
# Launches lynx with the logfile
# Deletes the log file

@echo off

call :inputbox "Please enter the missionary ids separated by colons as generated by the javascript console:" "Missionary IDs"
set ids=%Input%
call :inputbox "Please enter your lds username:" "LDS user name"
set name=%Input%
call :inputbox "Please enter your lds password:" "LDS password"
set pass=%Input%

echo %ids%

python make_lynx_script.py /home script.txt %ids% %name% %pass%
move script.txt "C:\cygwin\home\Office Elder 1\script.txt"
C:\cygwin\bin\bash  --login -c "bash lynx.sh"
move C:\cygwin\home\*.jpg "%cd%"
"C:\Program Files (x86)\IrFanView\i_view32.exe" *.jpg /resize=(112,135) /aspectratio /resample /convert=*.bmp
del "C:\cygwin\home\Office Elder 1\script.txt"
#del *.jpg

exit /b

:InputBox
set input=
set heading=%~2
set message=%~1
echo wscript.echo inputbox(WScript.Arguments(0),WScript.Arguments(1)) >"%temp%\input.vbs"
for /f "tokens=* delims=" %%a in ('cscript //nologo "%temp%\input.vbs" "%message%" "%heading%"') do set input=%%a
exit /b